config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/new'

  get 'views/index'

  get 'views/new'

  get 'views/create'

  get 'views/destroy'

  resources :sessions
  resources :users

  resources :links
  get 'welcome/index'

  root 'welcome#index'

  get "/:id" => 'welcome#show'
  get 'welcome/signup', as: 'sign_up'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :views
  validates :long_url, presence: :true
  validates :short_url, uniqueness: :true

  before_save :generate_short_url
  before_save :url_check

  def self.link_info(link_id, user_id)
    self.where(id: link_id, user_id: user_id)
  end

  private
    def url_check
      self.long_url = (self.long_url[0..3]=="http") ? self.long_url : "http://"+self.long_url
    end

    def generate_short_url
      begin
          url = SecureRandom.hex[0..4]
          self.short_url = url
      end while Link.exists?(short_url: url)
    end


    scope :recent_links, ->{select('short_url').where(user_id: 0).order('id desc').limit(5)}
    scope :top_links, ->{select('short_url').where(user_id: 0).order('views_count desc').limit(5)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links
  validates :email, presence: :true
  validates :username, presence: :true
  validates :email, uniqueness: :true
end

app/models/view.rb
class View < ActiveRecord::Base
  belongs_to :link, :counter_cache => true

  def self.top_countries(link_id)
    self.select('country, count("id") as count').where(link_id: link_id).order("count desc").group('country').limit(5)
  end

  def self.top_referrers(link_id)
    self.select('referrer, count("id") as count').where(link_id: link_id).order("count desc").group('referrer').limit(5)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end
  end



  rescue_from ::ActiveRecord::RecordNotFound, with: :record_not_found
  rescue_from ::ActionController::RoutingError, with: :no_route_found


  def no_route_found
    flash[:notice] = "Invalid address!"
    redirect_to root_path
  end

  def record_not_found(exception)
    flash[:notice] = exception.message.to_s
    redirect_to root_path
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_filter :set_links, :only=>[:show]

  def index
  end

  def show
    get_link_details(params[:id])
    redirect_to "/users/"+(session[:user_id]).to_s
  end

  def update
  end

  def check_referrer
    if request.env["HTTP_REFERER"].include? 'users'
       redirect_to users_path+"/#{session[:user_id]}"
     else
       render welcome_index_path
    end
  end

  def create
    @link = Link.new(link_params)
    @link.user_id = (current_user) ? session[:user_id] : 0
    @user_link = find_user_links(@link.long_url) if current_user
    unless @user_link
      if @link.save
        flash[:success] = "Url Successfully shortened"
        flash[:short_url] = @link.short_url
        get_link_details(@link.id)
        check_referrer
      end
    else
      flash[:success] = "Url Successfully shortened"
      flash[:short_url] = @user_link.short_url
      get_link_details(@user_link.id)
      check_referrer
    end
  end

  def new
    @link = Link.new
  end

  def get_link_details(id)
    flash[:link_info] = Link.link_info(id, session[:user_id]) if current_user
    flash[:country] = View.top_countries(id)
    flash[:referrer] = View.top_referrers(id)
  end

  private
  def find_user_links(long_url)
    long_url = (long_url[0..3]=="http") ? long_url : "http://"+long_url
    Link.find_by_long_url_and_user_id(long_url, session[:user_id])
  end

  def link_params
    params.require(:link).permit(:long_url)
  end

  def set_links
    @link = Link.find_by short_url: params[:id] || nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      user.last_sign_in_at = Time.now
      user.save!
      User.increment_counter :sign_in_count, user.id
      session[:user_id] = user.id
      session[:username] = user.username
      redirect_to user, notice: "Welcome"
    else
      flash[:notice] = "Wrong cridentials"
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    session[:username] = nil
    flash = nil
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, only: [:show]

  def show
    @user_link = @user.links.first
    if @user_link
      flash[:link_info] = Link.link_info(@user_link.id, session[:user_id]) unless flash[:link_info]
      flash[:country] = View.top_countries(@user_link.id) unless flash[:country]
      p flash[:country]
      flash[:referrer] = View.top_referrers(@user_link.id) unless flash[:referrer]
      p flash[:referrer]
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      session[:username] = @user.username
      redirect_to welcome_index_path
    else
      flash[:notice] = @user.errors
      redirect_to sign_up_path
    end
  end

  def destroy
  end

  def update
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :username)
    end

    def set_user
      @user = User.find(params[:id])
      redirect_to root_path if params[:id].to_i!=session[:user_id]
    end
end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_filter :set_links, :only=>[:show]

  def index
    @recents = Link.recent_links
    @top_links = Link.top_links
  end

  def show
    redirect_to @link.long_url
  end

  private
    def set_links
      @link = Link.find_by short_url: params[:id]
      if @link
        ViewWorker.perform_async(@link.id, request.referrer, request.remote_ip, request.location.country)
      else
        no_record_error
      end
    end

    def no_record_error
      flash[:notice] = "No record Found"
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_url(url)
    if url.length > 70
      url[0..70]+"..."
    else
      url
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/views_helper.rb
module ViewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def gethost
    host = (request.host=='localhost' || request.host=='lvh.me') ? request.host+":"+request.env["SERVER_PORT"] : request.host
    host = (host[0..3]=="http") ? host : "http://"+host
    host+"/"
  end
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-left">
        <% unless controller_name=="welcome" && action_name=="index"%>
          <h3><%= link_to "YouRl", root_path %></h3>
        <%end%>
      </ul>

      <% unless current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle our-focus" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color:white">Login <span class="caret"></span></a>
            <ul class="dropdown-menu user-form">
              <%= form_tag sessions_path do %>
                <div class="form-group">
                  <%= label_tag :email %>
                  <%= email_field_tag :email, params[:email], class: "form-control", placeholder: "email" %>
                </div>
                <div class="form-group">
                  <%= label_tag :password %>
                  <%= password_field_tag :password, params[:password], class: "form-control", placeholder: "password" %>
                </div>
                <%= submit_tag 'Login', class: "btn btn-primary"%>
              <% end %>
              </form>
            </ul>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="<%= sign_up_path %>" style='color:white'>Signup</a></li>
        </ul>
      <%else%>
        <ul class="nav navbar-nav navbar-right" style="margin-top:20px">
          <li role="presentation" class="dropdown">
            Welcome,
            <a class="dropdown-toggle white our-focus" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <%= session[:username] %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <%=link_to "Profile", "../users/#{session[:user_id]}", style: "display:block; color:black !important; text-align:center !important; text-decoration:none !important; margin-bottom:10px"%>
              <%=link_to "Logout", "#{sessions_path}/#{session[:user_id]}", :method => :delete, style: "display:block; color:black !important; text-align:center !important; text-decoration:none !important", class: "black"%>
            </ul>
          </li>
        </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yourl</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext','https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', 'https://cdn.shopify.com/s/files/1/0691/5403/t/82/assets/style.scss.css?16677709998824235896', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'https://cdn.shopify.com/s/files/1/0691/5403/t/82/assets/app.js?16677709998824235896', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body data-no-turbolink>

<%= yield %>

<!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/zeroclipboard/2.2.0/ZeroClipboard.Core.js"></script> -->
  <footer class="footer" style="margin-top:20px; background-color:whitesmoke; padding: 33px 0;">
    <div class="container">
      <p class="text-muted">Built By <a href="https://github.com/andela-ssunday" target="_blank">Stephen</a> for <a href="http://andela.com" target="_blank">Andela</a></p>
    </div>
  </footer>
</body>
</html>

app/views/links/_shortlink.html.erb
<div id="loader2">
  <% unless flash[:short_url].nil? %>
    <div name="short_url" class="short_url" style="width: 128% !important" > <%=link_to  "#{gethost+flash[:short_url]}", gethost+flash[:short_url], target: '_blank', style: "text-decoration:none" %> <span class="glyphicon glyphicon-share-alt sm" aria-hidden="true"></span></div>
  <% end %>
</div>

app/views/links/index.html.erb
<h1>Links#index</h1>
<p>Find me in app/views/links/index.html.erb</p>

app/views/links/new.html.erb
<h1>Links#new</h1>
<p>Find me in app/views/links/new.html.erb</p>

app/views/links/show.html.erb
<h1>Links#show</h1>
<p>Find me in app/views/links/show.html.erb</p>

app/views/links/update.html.erb
<h1>Links#update</h1>
<p>Find me in app/views/links/update.html.erb</p>

app/views/users/_link_info.html.erb
  <div class="wrap" >
      <div class="link-info">
      <!-- <h2>Google</h2> -->
      <% if flash[:link_info]%>
      <%#binding.pry%>
        <% @link_info = flash[:link_info][0]%>

          <h4><%= link_to "#{gethost+@link_info['short_url']}", gethost+@link_info["short_url"], 'data-turbolinks-track' => false, remote: false, target: '_blank' %></h4>
          <h5 style="word-wrap:break-word"><%= (@link_info["long_url"]) %></h5>
          <h6>Created at: <%= time_ago_in_words(@link_info["created_at"]) %> ago<h6>
        </div>
        <div class="traffic">
          <h5>Page views</h5>
          <span style="font-size:40px"><%= (@link_info["views_count"].nil?) ? 0 : @link_info["views_count"] %></span>
        </div>
        <% if flash[:country].size>0 %>
          <div class="ip">
              <span style="text-align:center">Top countries</span>
              <ul>
                <% flash[:country].each do |link| %>
                  <li><%= (link["country"].nil?) ? 'direct' : link["country"] %> <%#= "(#{link['count']})"%></li>
                <%end%>
              </ul>
          </div>
        <%end%>
        <% if flash[:referrer].size>0 %>
          <div class="ref">
              <span style="text-align:center">Top referrals</span>
              <ul>
                <% flash[:referrer].each do |link| %>
                  <li><%= (link["referrer"].nil?) ? 'direct' : link["referrer"] %></li>
                <%end%>
              </ul>
          </div>
        <%end%>
    <%end%>
  </div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div clas="container-fluid">
<%= render partial: "layouts/nav"%>
  <div class="container">
    <div class="row" style="height:800px">
      <div class="col-md-6 full-height">
        <div class="col-md-5 form-inline" style="margin-left: -15px">
            <%= form_for(Link.new) do |f| %>
            <div class="input-group">
              <%= f.text_field :long_url, class: "form-control our-form-control", id: "exampleInputEmail1",placeholder: "Enter long url", required: :true%>
              <span class="input-group-btn">
                <%= f.submit class: "btn btn-primary"%>
              </span>
            </div>
            <% end %>
          </div>
          <% unless flash[:short_url].nil? %>
            <input type="text" disabled="disabled" name="short_url" class="short_url" style="width: 100% !important" value=<%= gethost+flash[:short_url] %> >
          <% end %>

          <div class="header">
            <div class="list-group">

              <% if @user.links %>
                <% @user.links.each do |link|%>
                <% #binding.pry %>
                  <%=link_to "#{gethost+link.short_url}", "/links/#{link.id}",remote: true, class:( (flash[:link_info][0]["id"]==link.id) ? "list-group-item show my-active" : "list-group-item show") %>


                <%end%>
              <% end %>
            </div>
          </div>
      </div>
      <div class="col-md-5 full-height link_info" id="link_info" style="background-color:white">
        <div class="spinner" style="margin-top:250px;display:none">
          <div class="dot1"></div>
          <div class="dot2"></div>
        </div>

        <%= render partial: 'link_info' %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.js.erb
$("#link_info").html("<%= escape_javascript(render partial: 'link_info')%>")

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/views/create.html.erb
<h1>Views#create</h1>
<p>Find me in app/views/views/create.html.erb</p>

app/views/users/views/destroy.html.erb
<h1>Views#destroy</h1>
<p>Find me in app/views/views/destroy.html.erb</p>

app/views/users/views/index.html.erb
<h1>Views#index</h1>
<p>Find me in app/views/views/index.html.erb</p>

app/views/users/views/new.html.erb
<h1>Views#new</h1>
<p>Find me in app/views/views/new.html.erb</p>

app/views/welcome/index.html.erb
<div clas="container-fluid">
  <%= render partial: "layouts/nav"%>

  <div class="container">
    <div class="body" style="margin-bottom:200px">
      <% if flash[:notice] %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          <%= flash[:notice] %>
        </div>
      <%end%>
        <div class="alert alert-success succ" role="alert" style="display:none">
          <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
          <span class="sr-only">Success:</span>
          Link Shortened Successfully
        </div>
      <h1 class="center header">YouRL</h1>
      <div class="row">
        <div class="col-md-5 shrink form-inline" >
            <%= form_for(Link.new, remote: :true) do |f| %>
            <div class="input-group">
              <%= f.text_field :long_url, class: "form-control our-form-control", id: "exampleInputEmail1",placeholder: "Enter long url", required: :true%>
              <span class="input-group-btn">
                <%= f.submit class: "btn btn-primary index"%>
              </span>
            </div>
            <% end %>
            <div id="loader">
              <div class="spinner" style="margin-top:20px;display:none">
                <div class="dot1"></div>
                <div class="dot2"></div>
              </div>

            </div>
          </div>
        </div>
    </div>



    <div class="text-center">

      <!-- Nav tabs -->
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active" style="margin-left:40%"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Top Links</a></li>
        <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">Recent Links</a></li>
      </ul>

      <!-- Tab panes -->
      <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="home">
          <% if @top_links %>
              <% @top_links.each do |link|%>
                  <li class="list-group-item"><h4><%=link_to "#{gethost+link.short_url}", gethost+link.short_url, target: '_blank', style: "text-decoration:none" %></h4></li>
                <%end%>
          <%else%>
              <li>No links yet</li>
          <%end%>
        </div>
        <div role="tabpanel" class="tab-pane" id="profile">
          <% if @recents %>
              <% @recents.each do |link|%>
                  <li class="list-group-item"><h4><%= link_to "#{gethost+link.short_url}", gethost+link.short_url, target: '_blank', style: "text-decoration:none"  %></h4></li>
                <%end%>
          <%else%>
              <li>No links yet</li>
          <%end%>
        </div>
      </div>

    </div>


  </div>
</div>

app/views/welcome/index.js.erb
$("form[data-remote]").on("ajax:success", function(e, data, status, xhr){
  $("#loader").html("<%= escape_javascript(render partial: 'shortlink')%>")
  $(".short_url").fadeOut(30000)
})
  // $("#loader").load(location.href + " #loader2");

app/views/welcome/signup.html.erb
<div clas="container-fluid">
  <%= render partial: 'layouts/nav'%>

  <!-- <div class="main"> -->
    <div class="container">
      <% if flash[:notice] %>
        <div class="alert alert-danger" role="alert">
          <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
          <span class="sr-only">Error:</span>
          <%= flash[:notice] %>
        </div>
      <%end%>
      <div class='sign-up-form'>
        <div class="center header"><h2>Signup</h2></div>
        <%= form_for User.new do |f| %>
          <div class="form-group">
            <%= f.label :email, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :email, class: "form-control", placeholder: "Enter Email" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :username, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
            </div>
          </div>
          <div class="form-group">
            <%= f.label :password, class: "col-sm-2 control-label" %>
            <div class="col-sm-10">
              <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <button type="submit" class="btn btn-primary">Sign up</button>
            </div>
          </div>
        <% end %>
        </form>
      </div>
    </div>
  <!-- </div> -->

</div>